# Spring Main
spring.main.banner-mode=off

# Flyway
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# JWT Secret (shared)
application.security.jwt.secret-key=${JWT_SECRET_KEY}

# Security - exclude paths
application.security.exclude-paths=\
  /api/v1/auth/login,\
  /api/v1/auth/register,\
  /api/v1/auth/refresh-token,\
  /api/v1/spotify/auth/login,\
  /api/v1/spotify/auth/callback,\
  /api/v1/spotify/token/refresh

# Redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=${REDIS_PASSWORD}
spring.redis.timeout=6000ms

# Geocoding API
geocoding.api.base-url=https://api.geoapify.com/v1/geocode/search?format=json
geocoding.api.key=${GEOCODING_API_KEY}

# Weather API
weather.api.base-url=https://api.openweathermap.org/data/2.5/weather?
weather.api.key=${WEATHER_API_KEY}

# Spotify API config (shared)
spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
spotify.scope=playlist-modify-public
spotify.redirect-uri=${REDIRECT_URI}
spotify.auth-uri=https://accounts.spotify.com/authorize
spotify.api-token-base-url=https://accounts.spotify.com/api/token


redis.script.session.save=classpath:identity/adapter/redis/session_save.lua
redis.script.session.refresh=classpath:identity/adapter/redis/session_rotate.lua

