# Logging - minimal
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# Access token (prod)
identity.authentication.access-token.ttl=600s

# Refresh token (prod)
identity.authentication.session.ttl=1d

identity.authentication.cookies.refresh-token.name=refreshToken
identity.authentication.cookies.refresh-token.path=/api/v1/auth/token/refresh
identity.authentication.cookies.refresh-token.http-only=true
identity.authentication.cookies.refresh-token.secure=true
identity.authentication.cookies.refresh-token.same-site=Strict

identity.authentication.cookies.user-tag.name=userTag
identity.authentication.cookies.user-tag.path=/api/v1/auth/token/refresh
identity.authentication.cookies.user-tag.http-only=true
identity.authentication.cookies.user-tag.secure=true
identity.authentication.cookies.user-tag.same-site=Strict

# Spotify token cookie (prod)
spotify.access-token.expiration=3600
spotify.access-token.cookie.name=spotifyAccessToken
spotify.access-token.cookie.path=/api/v1/spotify
spotify.access-token.cookie.max-age=3600
spotify.access-token.cookie.http-only=true
spotify.access-token.cookie.secure=true
spotify.access-token.cookie.same-site=None