# Logging - verbose for debugging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Database (dev)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/skysong
spring.datasource.username=User
spring.datasource.password=${MYSQL_PASSWORD}

# Access token (dev)
identity.authentication.access-token.ttl=600s

# Refresh token (dev)
identity.authentication.refresh-token.duration=1d

application.security.refresh-token.cookie.name=refreshToken
application.security.refresh-token.cookie.path=/api/v1/auth/token/refresh
application.security.refresh-token.cookie.http-only=true
application.security.refresh-token.cookie.secure=false
application.security.refresh-token.cookie.same-site=Strict

# Spotify token cookie (dev)
spotify.access-token.expiration=3600
spotify.access-token.cookie.name=spotifyAccessToken
spotify.access-token.cookie.path=/api/v1/spotify
spotify.access-token.cookie.max-age=3600
spotify.access-token.cookie.http-only=true
spotify.access-token.cookie.secure=false
spotify.access-token.cookie.same-site=None