# Logging - minimal
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# Access token cookie (prod)
application.security.jwt.access-token.expiration=600
application.security.jwt.access-token.cookie.name=accessToken
application.security.jwt.access-token.cookie.path=/api
application.security.jwt.access-token.cookie.max-age=600
application.security.jwt.access-token.cookie.http-only=true
application.security.jwt.access-token.cookie.secure=true
application.security.jwt.access-token.cookie.same-site=Strict

# Refresh token cookie (prod)
application.security.refresh-token.expiration=1d
application.security.refresh-token.cookie.name=refreshToken
application.security.refresh-token.cookie.path=/api/v1/auth/token/refresh
application.security.refresh-token.cookie.max-age=86400
application.security.refresh-token.cookie.http-only=true
application.security.refresh-token.cookie.secure=true
application.security.refresh-token.cookie.same-site=Strict

# Spotify token cookie (prod)
spotify.access-token.expiration=3600
spotify.access-token.cookie.name=spotifyAccessToken
spotify.access-token.cookie.path=/api/v1/spotify
spotify.access-token.cookie.max-age=3600
spotify.access-token.cookie.http-only=true
spotify.access-token.cookie.secure=true
spotify.access-token.cookie.same-site=None