package com.mycompany.SkySong.shared.error;

import org.springframework.http.HttpStatus;

public enum ErrorType {
    // COMMMON ??
    EXTERNAL_API_TIMEOUT(HttpStatus.REQUEST_TIMEOUT),
    EXTERNAL_API_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    EXTERNAL_API_FORBIDDEN(HttpStatus.FORBIDDEN),
    EXTERNAL_API_UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    EXTERNAL_API_BAD_REQUEST(HttpStatus.BAD_REQUEST),
    EXTERNAL_API_CLIENT_ERROR(HttpStatus.BAD_REQUEST),
    EXTERNAL_API_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    EXTERNAL_API_RATE_LIMIT(HttpStatus.TOO_MANY_REQUESTS),
    EXTERNAL_API_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),

    GEOCODING_NO_RESULTS(HttpStatus.UNPROCESSABLE_ENTITY),
    GEOCODING_INCOMPLETE_RESPONSE(HttpStatus.UNPROCESSABLE_ENTITY),
    SPOTIFY_INVALID_RESPONSE(HttpStatus.UNPROCESSABLE_ENTITY),
    SPOTIFY_INVALID_REQUEST(HttpStatus.UNPROCESSABLE_ENTITY),

    IDENTITY_CONFIGURATION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    GEOCODING_INVALID_COORDINATES(HttpStatus.UNPROCESSABLE_ENTITY),

    WEATHER_INCOMPLETE_RESPONSE(HttpStatus.UNPROCESSABLE_ENTITY),
    WEATHER_NO_RESULTS(HttpStatus.UNPROCESSABLE_ENTITY),
    WEATHER_INVALID_VALUES(HttpStatus.UNPROCESSABLE_ENTITY),
    USER_REQUEST_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    MISSING_USER_ID(HttpStatus.UNPROCESSABLE_ENTITY),


    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    EXPIRED_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),

    API_FORBIDDEN(HttpStatus.FORBIDDEN),
    API_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    EXTERNAL_API_REQUEST_TIMEOUT(HttpStatus.REQUEST_TIMEOUT),
    API_BAD_REQUEST(HttpStatus.BAD_REQUEST),
    API_UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    API_TO_MANY_REQUESTS(HttpStatus.TOO_MANY_REQUESTS),

    REDIS_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    REDIS_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    VALIDATION_ERROR(HttpStatus.UNPROCESSABLE_ENTITY),


    ROLE_NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_REQUEST_INVALID(HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    FORBIDDEN(HttpStatus.FORBIDDEN),
    TOKEN_NOT_FOUND(HttpStatus.NOT_FOUND),
    UNPROCESSABLE_ENTITY(HttpStatus.UNPROCESSABLE_ENTITY),
    PERSISTENCE_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    BAD_GATEWAY(HttpStatus.BAD_GATEWAY),

    // rejestracja
    INVALID_USERNAME_FORMAT(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_EMAIL_FORMAT(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_PASSWORD_FORMAT(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_REGISTRATION_INPUT(HttpStatus.UNPROCESSABLE_ENTITY),

    USERNAME_EXIST(HttpStatus.CONFLICT),
    EMAIL_EXIST(HttpStatus.CONFLICT),
    DEFAULT_ROLE_NOT_FOUND(HttpStatus.INTERNAL_SERVER_ERROR),




    INVALID_LOGIN_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    SPOTIFY_SESSION_PERSISTENCE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),



    GATEWAY_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT),
    SESSION_STORE_FAILURE(HttpStatus.SERVICE_UNAVAILABLE),
    ROLE_CONFIGURATION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED);



    private final HttpStatus httpStatus;
    ErrorType(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus getHttpStatus() {
        return httpStatus;
    }
}
