package com.mycompany.skysong.core.error;

public enum ErrorType {

    // move mapping to global
    //remove http logic

    // and what with http specific errors??
    ACCESS_SNAPSHOT_NOT_FOUND(HttpStatus.INTERNAL_SERVER_ERROR),

    EXTERNAL_API_TIMEOUT(HttpStatus.REQUEST_TIMEOUT),
    EXTERNAL_API_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    EXTERNAL_API_FORBIDDEN(HttpStatus.FORBIDDEN),
    EXTERNAL_API_UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    EXTERNAL_API_BAD_REQUEST(HttpStatus.BAD_REQUEST),
    EXTERNAL_API_CLIENT_ERROR(HttpStatus.BAD_REQUEST),
    EXTERNAL_API_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    EXTERNAL_API_RATE_LIMIT(HttpStatus.TOO_MANY_REQUESTS),
    EXTERNAL_API_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),

    GEOCODING_NO_RESULTS(HttpStatus.UNPROCESSABLE_ENTITY),
    GEOCODING_INCOMPLETE_RESPONSE(HttpStatus.UNPROCESSABLE_ENTITY),
    SPOTIFY_INVALID_RESPONSE(HttpStatus.UNPROCESSABLE_ENTITY),
    SPOTIFY_INVALID_REQUEST(HttpStatus.UNPROCESSABLE_ENTITY),

    IDENTITY_CONFIGURATION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    GEOCODING_INVALID_COORDINATES(HttpStatus.UNPROCESSABLE_ENTITY),
    CONFLICT(HttpStatus.CONFLICT),
    SESSION_NOT_FOUND(HttpStatus.UNAUTHORIZED),

    WEATHER_INCOMPLETE_RESPONSE(HttpStatus.UNPROCESSABLE_ENTITY),
    WEATHER_NO_RESULTS(HttpStatus.UNPROCESSABLE_ENTITY),
    WEATHER_INVALID_VALUES(HttpStatus.UNPROCESSABLE_ENTITY),
    USER_REQUEST_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    MISSING_USER_ID(HttpStatus.UNPROCESSABLE_ENTITY),


    DATABASE_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    COOKIE_NOT_FOUND(HttpStatus.BAD_REQUEST),
    SERIALIZATION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    DESERIALIZATION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    SESSION_NOT_FOUND(HttpStatus.UNAUTHORIZED),
//    REFRESH_TOKEN_NOT_FOUND(HttpStatus.UNAUTHORIZED),


    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    EXPIRED_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),

    API_FORBIDDEN(HttpStatus.FORBIDDEN),
    API_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    EXTERNAL_API_REQUEST_TIMEOUT(HttpStatus.REQUEST_TIMEOUT),
    API_BAD_REQUEST(HttpStatus.BAD_REQUEST),
    API_UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    API_TO_MANY_REQUESTS(HttpStatus.TOO_MANY_REQUESTS),


    REDIS_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    REDIS_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    SPOTIFY_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND),
    MISSING_REQUIRED_FIELD(HttpStatus.UNPROCESSABLE_ENTITY),
    EXPIRED_JWT_TOKEN(HttpStatus.UNAUTHORIZED),
    INVALID_JWT_TOKEN(HttpStatus.UNAUTHORIZED),
    INVALID_ROLE_CODE(),
    DOMAIN_RULE_VIOLATION(HttpStatus.CONFLICT),



    ROLE_NOT_FOUND(HttpStatus.NOT_FOUND),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    FORBIDDEN(HttpStatus.FORBIDDEN),
    TOKEN_NOT_FOUND(HttpStatus.NOT_FOUND),
    UNPROCESSABLE_ENTITY(HttpStatus.UNPROCESSABLE_ENTITY),
    PERSISTENCE_ERROR(HttpStatus.SERVICE_UNAVAILABLE),
    BAD_GATEWAY(HttpStatus.BAD_GATEWAY),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    // rejestracja
    INVALID_USERNAME_FORMAT(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_EMAIL_FORMAT(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_PASSWORD_FORMAT(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_REGISTRATION_INPUT(HttpStatus.UNPROCESSABLE_ENTITY),

    USERNAME_EXIST(HttpStatus.CONFLICT),
    EMAIL_EXIST(HttpStatus.CONFLICT),
    DEFAULT_ROLE_NOT_FOUND(HttpStatus.INTERNAL_SERVER_ERROR),
    AUTHENTICATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    ACCOUNT_LOCKED(HttpStatus.UNAUTHORIZED),
    ACCOUNT_DISABLED(HttpStatus.UNAUTHORIZED),
    AUTHENTICATION_SERVICE_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    BAD_REQUEST(HttpStatus.BAD_REQUEST),

    INVALID_LOGIN_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    SPOTIFY_SESSION_PERSISTENCE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    INVARIANT_VIOLATION(HttpStatus.INTERNAL_SERVER_ERROR),// na pewno taki status ??
    USER_KEY_NOT_FOUND(HttpStatus.INTERNAL_SERVER_ERROR),
    SESSION_REVOKED(HttpStatus.UNAUTHORIZED),
    DATA_INTEGRITY_ERROR(HttpStatus.),
    JAKI_ERROR(HttpStatus.CONFLICT),
    SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),



    GATEWAY_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT),
    SESSION_STORE_FAILURE(HttpStatus.SERVICE_UNAVAILABLE),
    ROLE_CONFIGURATION_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    SESSION_EXPIRED(HttpStatus.UNAUTHORIZED),
    SESSION_OUTDATED(HttpStatus.UNAUTHORIZED),
    INVALID_SESSION(HttpStatus.UNAUTHORIZED);
}
